### ISSUE TITLE
Question regarding colored indentation columns

### ISSUE THREAD

**Issue by rebelskum** [diff001a/KawaiiTheme#2]
Hi, I love this theme so much! Its so wonderfully done, thank you! Only thing is that my indented columns aren't colored as shown in the screen shot of the theme. In screenshot, each indent has their own color, how do i get that to show up in my vs code editor with your theme? 
Thank you!

**Comment by diff001a** [comment]
Hi, thanks for your comment!! Actually this theme doesn't colorize the indentation. in this screenshot, I'm using [indent-rainbow](https://marketplace.visualstudio.com/items?itemName=oderwat.indent-rainbow) package! hope it helps you😊

**Comment by rebelskum** [comment]
Omg! thank you! I'm a huge fan of your theme 🥰 you've inspired me to do more coding! Thank you so much

**Comment by diff001a** [comment]
I'm very happy to hear that!! thank you😊
